# Generated by Django 5.2.5 on 2025-09-02 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clinic',
            },
        ),
        migrations.CreateModel(
            name='ScheduleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., IAP-2025', max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('source_url', models.URLField(blank=True, default='')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'schedule_version',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=120)),
                ('whatsapp_e164', models.CharField(help_text='Parent WhatsApp in E.164 format, e.g. +919812345678', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='vaccinations.clinic')),
            ],
            options={
                'db_table': 'parent',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='vaccinations.clinic')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vaccinations.parent')),
            ],
            options={
                'db_table': 'child',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Stable identifier, e.g., 'hep-b', 'dtap-dtwp', 'ipv'")),
                ('name', models.CharField(help_text="Display name, e.g., 'Hepatitis B'", max_length=120)),
                ('aliases', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccines', to='vaccinations.scheduleversion')),
            ],
            options={
                'db_table': 'vaccine',
            },
        ),
        migrations.CreateModel(
            name='VaccineDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_index', models.PositiveSmallIntegerField(help_text='Order within the vaccine')),
                ('dose_label', models.CharField(blank=True, default='', help_text="e.g., 'Dose 1', 'Booster', 'MMR-2'", max_length=60)),
                ('eligible_sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Restrict to a sex (e.g., HPV girls), else null for all.', max_length=1, null=True)),
                ('min_offset_days', models.PositiveIntegerField(help_text='Lower bound (inclusive) in days from birth')),
                ('max_offset_days', models.PositiveIntegerField(blank=True, help_text='Upper bound in days from birth (null = no upper bound)', null=True)),
                ('is_booster', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_dose', models.ForeignKey(blank=True, help_text='Required if is_booster=True; points to the prior dose.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booster_children', to='vaccinations.vaccinedose')),
                ('schedule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doses', to='vaccinations.scheduleversion')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doses', to='vaccinations.vaccine')),
            ],
            options={
                'db_table': 'vaccine_dose',
            },
        ),
        migrations.CreateModel(
            name='ChildDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_until_date', models.DateField(blank=True, null=True)),
                ('status_override', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='vaccinations.child')),
                ('dose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_doses', to='vaccinations.vaccinedose')),
            ],
            options={
                'db_table': 'child_dose',
            },
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['parent'], name='child_parent__16983e_idx'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['clinic'], name='child_clinic__5e8bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['date_of_birth'], name='child_date_of_670404_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccine',
            index=models.Index(fields=['schedule_version', 'name'], name='vaccine_schedul_e962e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vaccine',
            unique_together={('schedule_version', 'code')},
        ),
        migrations.AddIndex(
            model_name='vaccinedose',
            index=models.Index(fields=['schedule_version', 'vaccine', 'sequence_index'], name='vaccine_dos_schedul_5264c4_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccinedose',
            index=models.Index(fields=['previous_dose'], name='vaccine_dos_previou_fb1c9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='vaccinedose',
            constraint=models.CheckConstraint(condition=models.Q(('max_offset_days__isnull', True), ('max_offset_days__gte', models.F('min_offset_days')), _connector='OR'), name='vd_offset_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='vaccinedose',
            constraint=models.CheckConstraint(condition=models.Q(('previous_dose', models.F('id')), _negated=True), name='vd_prev_not_self'),
        ),
        migrations.AlterUniqueTogether(
            name='vaccinedose',
            unique_together={('schedule_version', 'vaccine', 'sequence_index')},
        ),
        migrations.AddIndex(
            model_name='childdose',
            index=models.Index(fields=['child'], name='child_dose_child_i_ed5ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='childdose',
            index=models.Index(fields=['dose'], name='child_dose_dose_id_86dd9f_idx'),
        ),
        migrations.AddIndex(
            model_name='childdose',
            index=models.Index(fields=['due_date'], name='child_dose_due_dat_9ba3ba_idx'),
        ),
        migrations.AddIndex(
            model_name='childdose',
            index=models.Index(fields=['given_date'], name='child_dose_given_d_d1586e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='childdose',
            unique_together={('child', 'dose')},
        ),
    ]
