# Generated by Django 5.2.5 on 2025-09-03 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='code',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='vaccinedose',
            name='dose_label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='vaccinedose',
            name='eligible_sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinedose',
            name='max_offset_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinedose',
            name='min_offset_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vaccinedose',
            name='previous_dose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booster_children', to='vaccinations.vaccinedose'),
        ),
        migrations.AlterField(
            model_name='vaccinedose',
            name='sequence_index',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
