# Generated by Django 5.2.5 on 2025-09-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0004_doctor_google_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=128, unique=True)),
                ('doctor_token', models.CharField(max_length=128)),
                ('next_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'oauth_state',
            },
        ),
        migrations.RenameIndex(
            model_name='doctor',
            new_name='doctor_clinic__492837_idx',
            old_name='idx_doctor_clinic',
        ),
        migrations.RenameIndex(
            model_name='doctor',
            new_name='doctor_partner_ca8c50_idx',
            old_name='idx_doctor_partner',
        ),
        migrations.RenameIndex(
            model_name='doctor',
            new_name='doctor_field_r_49986a_idx',
            old_name='idx_doctor_rep',
        ),
        migrations.RenameIndex(
            model_name='doctorsessiontoken',
            new_name='doctor_sess_doctor__e7a0d8_idx',
            old_name='idx_doc_sess_exp',
        ),
        migrations.RenameIndex(
            model_name='fieldrepresentative',
            new_name='field_repre_partner_e85b40_idx',
            old_name='idx_rep_partner_code',
        ),
        migrations.AlterField(
            model_name='clinic',
            name='languages_csv',
            field=models.CharField(blank=True, default='', help_text='Comma-separated language codes (e.g., en,hi,mr)', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='google_sub',
            field=models.CharField(blank=True, help_text='Google OIDC subject (unique account id).', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctorsessiontoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fieldrepresentative',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='oauthstate',
            index=models.Index(fields=['state', 'expires_at'], name='oauth_state_state_0354d4_idx'),
        ),
    ]
