# Generated by Django 5.2.5 on 2025-09-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0005_oauthstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthstate',
            name='redirect_uri',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
