# Generated by Django 5.2.5 on 2025-09-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0007_child_share_link'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='childsharelink',
            new_name='child_share_child_i_a28a1d_idx',
            old_name='idx_csl_child',
        ),
        migrations.RenameIndex(
            model_name='childsharelink',
            new_name='child_share_expires_97186c_idx',
            old_name='idx_csl_exp',
        ),
        migrations.AlterField(
            model_name='childsharelink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
