# Generated by Django 5.2.5 on 2025-09-18 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0008_rename_idx_csl_child_child_share_child_i_a28a1d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineEducationDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, default='en', max_length=5)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('video_url', models.URLField()),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('other', 'Other')], default='vimeo', max_length=20)),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_education', to='vaccinations.vaccine')),
            ],
            options={
                'db_table': 'vaccine_education_doctor',
                'indexes': [models.Index(fields=['vaccine', 'rank'], name='vaccine_edu_vaccine_f09e3c_idx'), models.Index(fields=['is_active'], name='vaccine_edu_is_acti_7524ff_idx')],
                'unique_together': {('vaccine', 'video_url')},
            },
        ),
        migrations.CreateModel(
            name='VaccineEducationPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, help_text='ISO 639-1 code (e.g. en, hi, mr, bn, gu, ta, te, kn, ml).', max_length=5)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('video_url', models.URLField()),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('other', 'Other')], default='youtube', max_length=20)),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('rank', models.PositiveSmallIntegerField(default=1, help_text='Lower = show first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_education', to='vaccinations.vaccine')),
            ],
            options={
                'db_table': 'vaccine_education_patient',
                'indexes': [models.Index(fields=['vaccine', 'language', 'rank'], name='vaccine_edu_vaccine_a5e22a_idx'), models.Index(fields=['is_active'], name='vaccine_edu_is_acti_14108b_idx')],
                'unique_together': {('vaccine', 'language', 'video_url')},
            },
        ),
    ]
