# Generated by Django 5.2.5 on 2025-09-21 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0009_vaccineeducationdoctor_vaccineeducationpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdose',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childdose',
            name='last_reminder_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders_sent', to='vaccinations.doctor'),
        ),
        migrations.AddField(
            model_name='childdose',
            name='last_reminder_for_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='education_doctor_vimeo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='education_parent_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
