# Generated by Django 5.2.6 on 2025-09-25 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0010_childdose_last_reminder_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'ui_string',
            },
        ),
        migrations.CreateModel(
            name='UiStringTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=5)),
                ('text', models.TextField()),
                ('ui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vaccinations.uistring')),
            ],
            options={
                'db_table': 'ui_string_translation',
                'unique_together': {('ui', 'language')},
            },
        ),
    ]
