# Generated by Django 5.2.6 on 2025-09-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0011_uistring_uistringtranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinedose',
            name='anchor_policy',
            field=models.CharField(choices=[('A', 'AGE_ONLY'), ('L', 'LATER_OF_AGE_AND_INTERVAL'), ('I', 'INTERVAL_ONLY')], db_index=True, default='L', max_length=1),
        ),
        migrations.AddIndex(
            model_name='vaccinedose',
            index=models.Index(fields=['vaccine', 'sequence_index'], name='vaccine_dos_vaccine_209e15_idx'),
        ),
    ]
