# Generated by Django 5.2.5 on 2025-09-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0012_vaccinedose_anchor_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinedose',
            name='series_key',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='vaccinedose',
            name='series_seq',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
    ]
