# Generated by Django 5.2.5 on 2025-10-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0019_add_encrypted_columns'),
        ('vaccinations', '0020_patient_encrypted_columns'),
    ]

    operations = [
    ]
