# Generated by Django 5.2.5 on 2025-10-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0021_merge_20251006_1959'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['clinic'], name='idx_child_clinic'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['date_of_birth'], name='idx_child_dob'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['parent'], name='idx_child_parent'),
        ),
        migrations.AlterModelTable(
            name='parent',
            table='parent',
        ),
    ]
