# Generated by Django 5.2.5 on 2025-10-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0022_child_idx_child_clinic_child_idx_child_dob_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'managed': True},
        ),
    ]
