# Generated by Django 5.2.5 on 2025-10-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0023_alter_doctor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
    ]
