# Generated by Django 5.2.5 on 2025-10-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0024_alter_doctor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'managed': True},
        ),
    ]
