# Generated by Django 5.2.5 on 2025-10-06 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0025_alter_doctor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='child',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
