# Generated by Django 5.2.5 on 2025-10-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0027_auto'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='childsharelink',
            new_name='child_share_child_i_a28a1d_idx',
            old_name='vaccinations_child_id_idx',
        ),
        migrations.RenameIndex(
            model_name='childsharelink',
            new_name='child_share_expires_97186c_idx',
            old_name='vaccinations_expires_at_idx',
        ),
    ]
