# Generated by Django 5.2.5 on 2025-10-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0027_auto'),
    ]

    operations = []
